name: main
on: [pull_request]
jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
    - name: "Saying Hi"
      run: echo "Hi"
  actionlint:
    runs-on: ubuntu-latest
    steps:
    - name: actionlint with reviewdog
      uses: reviewdog/action-actionlint@v1.36.0
